### ISSUE TITLE
Datenschutzhinweis Kontaktformular

### ISSUE THREAD

**Issue by adlerweb** [FreifunkMYK/landingpage#4]
Hinweis einbringen, dass die eingegebenen Daten veröffentlicht werden

**Comment by kreativmonkey** [comment]
Ich habe ein feld zur einverständnis in den Datenschutz hinzugefügt. In einem Link wird erläutert was mit den Daten geschieht und wer sie erhält und warum. Damit sollte dieser fehler behoben sein!
